// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_inscription::candidate_inscription_put_up_v2 {

    use std::string::String;
    use sui::object::{Self, ID};
    use sui_inscription::slot::{Self, CandidateInscriptionPutUpV2};

    public fun id(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): object::ID {
        slot::candidate_inscription_put_up_v2_id(candidate_inscription_put_up_v2)
    }

    public fun slot_number(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u8 {
        slot::candidate_inscription_put_up_v2_slot_number(candidate_inscription_put_up_v2)
    }

    public fun candidate_inscription_id(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): ID {
        slot::candidate_inscription_put_up_v2_candidate_inscription_id(candidate_inscription_put_up_v2)
    }

    public fun round(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u64 {
        slot::candidate_inscription_put_up_v2_round(candidate_inscription_put_up_v2)
    }

    public fun candidate_hash(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): vector<u8> {
        slot::candidate_inscription_put_up_v2_candidate_hash(candidate_inscription_put_up_v2)
    }

    public fun candidate_inscriber(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): address {
        slot::candidate_inscription_put_up_v2_candidate_inscriber(candidate_inscription_put_up_v2)
    }

    public fun candidate_timestamp(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u64 {
        slot::candidate_inscription_put_up_v2_candidate_timestamp(candidate_inscription_put_up_v2)
    }

    public fun candidate_amount(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u64 {
        slot::candidate_inscription_put_up_v2_candidate_amount(candidate_inscription_put_up_v2)
    }

    public fun candidate_nonce(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u128 {
        slot::candidate_inscription_put_up_v2_candidate_nonce(candidate_inscription_put_up_v2)
    }

    public fun candidate_difference(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): u64 {
        slot::candidate_inscription_put_up_v2_candidate_difference(candidate_inscription_put_up_v2)
    }

    public fun candidate_content(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): String {
        slot::candidate_inscription_put_up_v2_candidate_content(candidate_inscription_put_up_v2)
    }

    public fun successful(candidate_inscription_put_up_v2: &CandidateInscriptionPutUpV2): bool {
        slot::candidate_inscription_put_up_v2_successful(candidate_inscription_put_up_v2)
    }

}
