// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_inscription::inscription_deleted {

    use sui::object;
    use sui_inscription::inscription::{Self, InscriptionDeleted};

    public fun id(inscription_deleted: &InscriptionDeleted): object::ID {
        inscription::inscription_deleted_id(inscription_deleted)
    }

}
