// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_inscription::inscription_aggregate {
    use std::string::String;
    use sui::tx_context;
    use sui_inscription::inscription;
    use sui_inscription::inscription_mint_logic;

    public entry fun mint(
        hash: vector<u8>,
        slot_number: u8,
        round: u64,
        inscriber: address,
        timestamp: u64,
        amount: u64,
        content: String,
        ctx: &mut tx_context::TxContext,
    ) {
        let inscription_minted = inscription_mint_logic::verify(
            hash,
            slot_number,
            round,
            inscriber,
            timestamp,
            amount,
            content,
            ctx,
        );
        let inscription = inscription_mint_logic::mutate(
            &inscription_minted,
            ctx,
        );
        inscription::set_inscription_minted_id(&mut inscription_minted, inscription::id(&inscription));
        inscription::share_object(inscription);
        inscription::emit_inscription_minted(inscription_minted);
    }

}
