// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_inscription::slot_advanced {

    use sui::object;
    use sui_inscription::slot::{Self, SlotAdvanced};

    public fun id(slot_advanced: &SlotAdvanced): object::ID {
        slot::slot_advanced_id(slot_advanced)
    }

    public fun slot_number(slot_advanced: &SlotAdvanced): u8 {
        slot::slot_advanced_slot_number(slot_advanced)
    }

    public fun round(slot_advanced: &SlotAdvanced): u64 {
        slot::slot_advanced_round(slot_advanced)
    }

}
